config/routes.rb
PhotoManagement::Application.routes.draw do
  get "users/new"

  resources :photos
  resources :albums do
    get 'settings', :on => :collection
  end
  resources :comments
  resources :users
  resources :sessions
  root :to => 'sessions#new'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :name, :description
  has_many :photos
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :description, :photo_id
  has_one :photo
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :photo, :name, :description, :album_id
  validates_presence_of :photo
  has_attached_file :photo, :styles => {:thumb => "120x120>", :small => "200x200>", :large => "600x400>"}
  has_many :comments
  has_one :album
end

app/models/user.rb
class User < ActiveRecord::Base
  	attr_accessible :email, :password_hash, :password_salt, :password, :password_confirmation
  	attr_accessor :password, :password_confirmation
  	validates_confirmation_of :password
  	validates_presence_of :password, :on => :create
  	validates_presence_of :email
  	validates_uniqueness_of :email

  	before_save :encrypt_password

  	def encrypt_password
    	if password.present?
      		self.password_salt = BCrypt::Engine.generate_salt
      		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    	end
  	end

	def self.authenticate(email, password)
  		user = find_by_email(email)
  		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
    		user
  		else
    		nil
  		end
	end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

	def new
		@album = Album.new
	end

	def create
		@album = Album.new(params[:album])
		@album.save
		redirect_to albums_path
	end

	def index
		@albums = Album.all
	end

	def show
		@album = Album.find_by_id(params[:id])
	end

	def settings
		UserNotifier.test_mail("ranga.435@gmail.com").deliver
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
		@comment = Comment.new
	end

	def create
		@comment = Comment.new(params[:comment])
		@comment.save
		redirect_to photo_path(@comment.photo_id)
	end
	
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def index
		@photos = Photo.all
	end

	def new
		@photo = Photo.new
		@photo.album_id = params[:album_id]
	end

	def create
		@photo = Photo.new(params[:photo])
		@photo.save
		redirect_to album_path(@photo.album_id)
	end

	def show
		@photo = Photo.find_by_id(params[:id])
	end

	def edit
		@photo = Photo.find_by_id(params[:id])
	end

	def update
		@photo = Photo.find_by_id(params[:id])
		if @photo.update_attributes(params[:photo])
			redirect_to @photo
		end
	end

	def destroy
		@photo = Photo.find_by_id(params[:id])
		@photo.destroy
		redirect_to photos_path
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		@user = User.authenticate(params[:email], params[:password])
		if @user
			session[:user_id] = @user.id
      		redirect_to photos_url, :notice => "Logged in!"
      	else
      		flash.now.alert = "Invalid email or password"
      		render "new"
  		end
	end

	def destroy
  		session[:user_id] = nil
  		redirect_to root_url, :notice => "Logged out!"
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def gmail_date_format(date)
    unless date.blank?  
      Time.zone.now.beginning_of_day <= date ?
      date.strftime('%I').to_i.to_s + date.strftime(':%M ') + date.strftime('%p').downcase :
      Time.zone.now.beginning_of_year <= date ?
      date.strftime('%b ') + date.day.to_s :
      date.strftime('%x')
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def date_format(date)
    if date.present?
      date.strftime('%d/%m/%y')
    end
  end

  def active_tab(name, controller)
    case name

    when "Photos"
      case controller
      when "photos"
        return "active"
      else
        return ""
      end

    when "Albums"
      case controller
      when "albums"
        return "active"
      else
        return ""
      end

    when "Comments"
      case controller
      when "comments"
        return "active"
      else
        return ""
      end

    else
      return ""
    end
  

  end
	
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
	def photo_name(photo, size)
		if photo
			image_tag photo.photo.url(size)
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<p><%= link_to "Add Album", new_album_path %></p>
<div class="page-unit">
<p>Total Albums: <%= @albums.size %></p>
<table class="table">
	<th>ID</th>
	<th>Name</th>
	<th>Description</th>
	<th>No of Photos</th>
	<th>Created</th>
	<th>Updated</th>
	<% @albums.each do |album| %>
		<tr><td><%= album.id %></td>
		<td><%= link_to album.name, album_path(album.id) %></td>
		<td><%= album.description %></td>
		<td><%= album.photos.size %></td>
		<td><%= date_format(album.created_at) %></td>
		<td><%= date_format(album.updated_at) %></td></tr>
	<% end %>
</table>
</div>

app/views/albums/new.html.erb
<%= form_for @album, :html => { :class => 'form' }  do |f| %>
	<div class="control-group">
		<%= f.label :name, "Abum Name" %>
		<%= f.text_field :name, :class => "input-large" %>
    </div>
    <div class="control-group">
		<%= f.label :description, "Description" %>
		<%= f.text_area :description, :rows => "3", :class => "input-large" %>
    </div>
	<%= f.submit "Save", :class => "btn" %>
	<%= link_to "Cancel", albums_path, :class => "btn" %>
<% end %>


<%= javascript_include_tag 'jquery.validate.min.js' %> 
<script type="text/javascript">
$(function() {
	
    $(".form").validate({
    	
        rules: { 
            "album[name]": "required",
            "album[description]": "required"
        },
        messages: { 
            "album[name]": "required",
            "album[description]": "required"
        },

        errorPlacement: function(error, element) { 
            error.appendTo(element.after("required")); 
        } 

    });
});

</script>

app/views/albums/settings.html.erb
<pre>successfully sent your message</pre>

app/views/albums/show.html.erb
<%= link_to "Add photo", new_photo_path(:album_id => @album.id) %>
<p>
	Album Name :<%= @album.name %><br/>
	Description :<%= @album.description %>
</p>
<p>Photos of this album</p>
<% if @album.photos %>
	<% @album.photos.each do |photo| %>
		<%= link_to photo_name(photo, "thumb"), photo_path(photo) %>
	<% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for Comment.new, :class => "form-inline" do |f| %>
	
    <div class="control-group">
		<%= f.label :description, "Description" %>
		<%= f.text_area :description, :rows => "3", :class => "input-large" %>
    </div>
    <%= f.hidden_field :photo_id, :value => photo.id %>
	<%= f.submit "Add Comment", :class => "btn" %>
	<%= link_to "Cancel", "#", :class => "btn cancel_comment" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoManagement</title>
  
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= stylesheet_link_tag    "bootstrap" %>
    <%= javascript_include_tag "bootstrap" %>
    <%= javascript_include_tag "bootstrap.min" %>
    <%= javascript_include_tag "jquery.min" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

  </head>
  <body>

    <% if current_user %>
      <div class="navbar navbar-inverse">
        <div class="navbar-inner">
          <ul class="nav">
             <li><%= link_to "Add Album", new_album_path %></li>
             <li><%= link_to "Albums", albums_url %></li>
             <li><%= link_to "Settings", settings_albums_path %></li>
            <li><%= link_to "Log Out",  log_out_path %></li>
          </ul>
        </div>
      </div>
    

    <div class="unit">
      <p>Loged in as :<%= current_user.email %></p>
      <p>Photo Management System</p>
      <ul class="nav nav-tabs" id="myTab">
        <li class= <%= active_tab("Photos", controller.controller_path) %> ><%= link_to "Photos", photos_url %></li>
        <li class= <%= active_tab("Albums", controller.controller_path) %> ><%= link_to "Albums", albums_url %></li>
        <li class= <%= active_tab("Comments", controller.controller_path) %> ><%= link_to "Comments", comments_url %></li>
      </ul>
    
    

      <div class="page-unit">
	     <%= yield %>
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash#{name}" %>
        <% end %>
      </div>
    </div>

    <div class="app-footer">
      Created By Ramans, If you have any problem contact this number 9505010200(Ramans)
    </div>

    <% else %>

      <div class="logged">
        <div style="text-align:right;padding:5px;">
            <% if @user.blank? %>
                <%= link_to "Sign Up",  sign_up_path, :class => "btn" %>
            <% else %>
                <%= link_to "Login",  root_url, :class => "btn" %>
            <% end %>
        </div>
        <%= yield %>
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash#{name}" %>
        <% end %>
        
      </div>

    <% end %>
    
  </body>
</html>

app/views/photos/edit.html.erb
<%= form_for @photo, :html => { :class => 'form' } do |f| %>
	<div class="control-group">
		<%= f.label :name, "Photo Name" %>
		<%= f.text_field :name, :class => "input-large" %>
    </div>
    <div class="control-group">
		<%= f.label :description, "Description" %>
		<%= f.text_area :description, :rows => "3", :class => "input-large" %>
    </div>
    <div class="control-group">
		<%= f.label :photo, "Upload Photo" %>
		<%= f.file_field :photo %>
	</div>
	<%= f.submit "Save", :class => "btn" %>
	<%= link_to "Cancel", photo_path(@photo.id), :class => "btn" %>
<% end %>

<%= javascript_include_tag 'jquery.validate.min.js' %> 
<script type="text/javascript">
$(function() {
	
    $(".form").validate({
    	
        rules: { 
            "photo[name]": "required",
            "photo[photo]": "required"
        },
        messages: { 
            "photo[name]": "required",
            "photo[photo]": "required"
        },

        errorPlacement: function(error, element) { 
            error.appendTo(element.after(" required")); 
        } 

    });
});

</script>

app/views/photos/index.html.erb
<% if @photos.present? %>
    <div id="myCarousel" class="carousel slide">
        <div class="carousel-inner">
        	<div class="active item">
                <center>
                    <%= link_to photo_name(@photos.first, "large"), photo_url(@photos.first.id) %>
                </center>
            </div>
        	<% @photos.each do |photo| %>
    		  <div class="item"><center><%= link_to photo_name(photo, "large"), photo_url(photo.id) %></center></div>
    		<% end %>
        </div>

        <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>

    </div>
<% else %>
    <p>No Photos</p>
<% end %>
<script type="text/javascript">
$(function() {
    $('.carousel').carousel({
        interval: "100"
    });
});
</script>

app/views/photos/new.html.erb
<%= form_for @photo, :html => { :class => 'form' }  do |f| %>
	<div class="control-group">
		<%= f.label :name, "Photo Name" %>
		<%= f.text_field :name, :class => "input-large" %>
    </div>
    <div class="control-group">
		<%= f.label :description, "Description" %>
		<%= f.text_area :description, :rows => "3", :class => "input-large" %>
    </div>
    <div class="control-group">
		<%= f.label :photo, "Upload Photo" %>
		<%= f.file_field :photo %>
	</div>
    <%= f.hidden_field :album_id, :class => "input-large" %>
	<%= f.submit "Save", :class => "btn" %>
	<%= link_to "Cancel", photos_path, :class => "btn" %>
<% end %>


<%= javascript_include_tag 'jquery.validate.min.js' %> 
<script type="text/javascript">
$(function() {
	
    $(".form").validate({
    	
        rules: { 
            "photo[name]": "required",
            "photo[photo]": "required"
        },
        messages: { 
            "photo[name]": "required",
            "photo[photo]": "required"
        },

        errorPlacement: function(text_warning, element) { 
            text_warning.appendTo(element.after("required")); 
        } 

    });
});

</script>

app/views/photos/show.html.erb
<% if @photo %>
	<p>Photo Name : <%= @photo.name %></p>
	<p>Description : <%= @photo.description %></p>
	<%= image_tag @photo.photo.url(:small) %></p>
	<%= link_to "Edit", edit_photo_path(@photo.id), :class => "btn" %>
	<%= link_to "Delete", photo_path(@photo), :method => "delete", :confirm => "Are you sure you want to Delete this photo", :class => "btn" %>
	<%= link_to "Add Comment", "#", :class => "btn", :id => "newnote" %>

	<div id="new_note_view" style="padding-top:10px;display:none;">
        <%= render :partial => "comments/form", :locals => { :photo => @photo } %>
    </div><br/><br/>
    
    <div>
        <pre><strong>Comments:</strong>
            <% @photo.comments.each do |comment| %>
    	    <%= comment.description %>,  Created on : <%= gmail_date_format(comment.created_at) %>
            <% end %>
        </pre>
    </div>
<% else %>
	<p>Page Not Found</p>
<% end %>

<script type="text/javascript" >
$(function() {
    
    $("#newnote").click(function() {
     	$("#new_note_view").show(); 
    });

    $(".cancel_comment").click(function() {
    	$("#new_note_view").hide();
    });
});
</script>

app/views/user_notifier/test_mail.html.erb
<p>
My Lover Photo
<%= link_to photo_name(@photo, "original"), photo_path(@photo) %>
</p>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
    <div class="error_message">
        <h2>Form is invalid</h2>
        <ul>
            <div style="text-align:left;padding-left:140px;">
                <% for message in @user.errors.full_messages %>
                  <li><%= message %></li>
                <% end %>
            </div>
        </ul>
    </div>
  <% end %>
    <div style="text-align:left;padding-left:140px;">
        <%= f.label :email %>
        <%= f.text_field :email %>
        <%= f.label :password %>
        <%= f.password_field :password %>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
    </div>
    <%= f.submit "Create", :class => "btn" %>
<% end %>